config/routes.rb
Rails.application.routes.draw do

  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:new, :create, :show]

  get 'carts/edit'

  get '/shop' => 'storefront#index'

  get '/about' => 'storefront#about'

  devise_for :users
  namespace :admin do
    resources :products
    resources :categories
    resources :brands
end

  root 'storefront#about'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :category
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  validates :name, presence: true, length: {minimum: 1}
  validates :price, presence: true, numericality: true, :format => { :with => /\A\d{1,4}(\.\d{0,2})?\z/ }
  validates :quantity, presence: true, length: {minimum: 1}, numericality: { only_integer: true }
  validates :description, presence: true

  has_attached_file :avatar, :styles => {
    :large => "350x350>",
    :medium => "250x250#",
    :thumb => "100x100#"
    },
    :default_url => "missing_:style.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search_by_name_or_description(string)
    where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%")
  end

private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/Admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand_id, :category_id, :avatar)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand_id, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/Admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :quantity %>
    <%= f.input :description %>
    <%= f.association :brand %>
    <%= f.association :category %>
    <%= f.input :avatar, as: :file, label: "Upload a product image" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/Admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_url(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/Admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products for Sale</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Main Photo</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |admin_product| %>
      <tr>
        <td><%= image_tag admin_product.avatar.url (:thumb) %></td>
        <td><%= admin_product.name %></td>
        <td><%= number_to_currency admin_product.price %></td>
        <td><%= admin_product.quantity %></td>
        <td><%= admin_product.description %></td>
        <td><%= admin_product.brand.try(:name) %></td>
        <td><%= admin_product.category.try(:name) %></td>
        <td><%= link_to (fa_icon "eye"), admin_product_path(admin_product) %></td>
        <td><%= link_to (fa_icon "pencil-square-o"), edit_admin_product_path(admin_product) %></td>
        <td><%= link_to (fa_icon "trash-o"), admin_product_path(admin_product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path, class: 'btn btn-large btn-info' %>

app/views/Admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/Admin/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>

<%= image_tag @product.avatar.url (:large) %>

</p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand.try(:name) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.try(:name) %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>